component_depth: 1
languages:
- javascript
- csharp
exclude:
- .*/Scripts/.*
- .*/packages/.*
- .*/obj/.*
- .*/deployment/.*
- .*/bin/.*
- .*/TestApplication/.*
- .*/Resource.designer.cs
- .*/FrontEndPackage/.*
- .*/Web/.*