component_depth: 1
languages:
- javascript
- csharp
exclude:
- .*/Scripts/.*
- .*/packages/.*
- .*/obj/.*
- .*/deployment/.*
- .*/bin/.*
- /Multichain/TestApplication/.*
- /Multichain/Unit Tests/.*
- .*/Resource.designer.cs