//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stoneycreek.Services.Blockchain.DataAccess.DataCom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlockChainEntities : DbContext
    {
        public BlockChainEntities()
            : base("name=BlockChainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientKeypairs> ClientKeypairs { get; set; }
        public virtual DbSet<CommunicationSubscription> CommunicationSubscription { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Streams> Streams { get; set; }
    }
}
