//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stoneycreek.Services.Blockchain.DataAccess.DataCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationSubscription
    {
        public decimal id { get; set; }
        public decimal ClientId { get; set; }
        public string SignalRIdentification { get; set; }
        public System.TimeSpan SubscriptionTime { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public decimal SubscriptionTimeOut { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
