//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stoneycreek.Services.Blockchain.DataAccess.DataCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public decimal id { get; set; }
        public decimal ClientId { get; set; }
        public string KeyIdentifier { get; set; }
        public string TransactionId { get; set; }
        public string Signature { get; set; }
        public System.TimeSpan TransactionTime { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal StreamId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Streams Streams { get; set; }
    }
}
